// boards
export const CREATED_BOARD = "CREATED_BOARD";
export const DELETED_BOARD = "DELETED_BOARD";
export const FETCHED_USER_BOARDS = "FETCHED_USER_BOARDS";
export const CHANGED_BOARD_TITLE = "CHANGED_BOARD_TITLE";

// panels
export const CREATED_PANEL = "CREATED_PANEL";
export const DELETED_PANEL = "DELETED_PANEL";
export const CHANGED_PANEL_TITLE = "CHANGED_PANEL_TITLE";

// tasks
export const CREATED_TASK = "CREATED_TASK";
export const DELETED_TASK = "DELETED_TASK";
export const CHANGED_TASK_TITLE = "CHANGED_TASK_TITLE";


// auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// UI
export const UI_LOADING_INIT = "UI_LOADING_INIT";
export const UI_LOADING_COMPLETE = "UI_LOADING_COMPLETE";
