// boards
export const CREATED_BOARD = "CREATED_BOARD";
export const DELETED_BOARD = "DELETED_BOARD";
export const BOARD_ERR = "BOARD_ERR";
export const CHANGED_BOARD_TITLE = "CHANGED_BOARD_TITLE";

// panels
export const CREATED_PANEL = "CREATED_PANEL";
export const DELETED_PANEL = "DELETED_PANEL";
export const CHANGED_PANEL_TITLE = "CHANGED_PANEL_TITLE";
export const PANEL_ERR = "PANEL_ERR";

// tasks
export const CREATED_TASK = "CREATED_TASK";
export const DELETED_TASK = "DELETED_TASK";
export const EDITED_TASK = "EDITED_TASK";

// auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// ui
export const UI_LOADING_INIT = "UI_LOADING_INIT";
export const UI_LOADING_COMPLETE = "UI_LOADING_COMPLETE";
export const CLEARED_NOTIFICATION = "CLEAR_NOTIFICATION";
export const SET_NOTIFICATION = "SET_NOTIFICATION";


// timer
export const START_TIMER = "START_TIMER";
export const STOP_TIMER = "STOP_TIMER";
export const SET_TIMER_TARGET = "SET_TIMER_TARGET";
export const UNSET_TIMER_TARGET = "UNSET_TIMER_TARGET";
